### ISSUE TITLE
获取到的内容不太对啊

### ISSUE THREAD

**Issue by hclasmn** [doupoa/GetEPICFreeGames#1]
![image](https://user-images.githubusercontent.com/32213103/132780481-52e46244-4041-4536-b3f9-835012b78f76.png)
本周yi应该是仁王啊，而且没游戏链接挺麻烦的，不知道作者能加上么

**Comment by doupoa** [comment]
感谢你的回复，这个问题我早就注意到了。沙皮E宝更改了数据获取方式，每次请求都会返回最近6条的数据。即使有些已经过期了。我想应该要加一个时间判断，但我最近太忙，感谢你的提醒，等到有空我会将时间判断加上去的。你也可以将解析数据中for的3次循环更改为6次循环以查看完整数据。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月10日(周五) 上午8:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [doupoa/GetEPICFreeGames] 获取到的内容不太对啊 (#1)




 

 本周yi应该是仁王啊，而且没游戏链接挺麻烦的，不知道作者能加上么
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
